In [2]:
import numpy as np 
import pandas as pd 
from sklearn.metrics import confusion_matrix 
from sklearn.model_selection import train_test_split 
from sklearn.tree import DecisionTreeClassifier 
from sklearn.metrics import accuracy_score 
from sklearn.metrics import classification_report 
  
# Function importing Dataset 
def importdata(): 
    balance_data = pd.read_csv( '/home/karthik/anaconda_python/411631_kelab_record/411631_python_using/classification/DecisionTree/input.txt', sep= ',') 
      
    new_data = {"wk_c":{"a":1,"b":2,"c":3,"d":4,"e":5,"f":6,"g":7,"h":8},
                 "wr_c":{"a":1,"b":2,"c":3,"d":4,"e":5,"f":6,"g":7,"h":8},
                 "bk_c":{"a":1,"b":2,"c":3,"d":4,"e":5,"f":6,"g":7,"h":8}}
    balance_data.replace(new_data,inplace=True)
    # Printing the dataswet shape 
    print ("Dataset Lenght: ", len(balance_data)) 
    print ("Dataset Shape: ", balance_data.shape) 
      
    # Printing the dataset obseravtions 
    print ("Dataset: ",balance_data.head()) 
    return balance_data 
  
    
    
    
# Function to split the dataset 
def splitdataset(balance_data): 
  
    # Seperating the target variable 
    X = balance_data.values[:,0:6] 
    Y = balance_data.values[:,6] 
  
    # Spliting the dataset into train and test 
    X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size = 0.3, random_state = 100) 
      
    return X, Y, X_train, X_test, y_train, y_test 
      
# Function to perform training with giniIndex. 
def train_using_gini(X_train, X_test, y_train): 
  
    # Creating the classifier object 
    clf_gini = DecisionTreeClassifier(criterion = "gini",random_state = 100,max_depth=None, min_samples_leaf=5) 
  
    # Performing training 
    clf_gini.fit(X_train, y_train) 
    return clf_gini 
      
# Function to perform training with entropy. 
def tarin_using_entropy(X_train, X_test, y_train): 
  
    # Decision tree with entropy 
    clf_entropy = DecisionTreeClassifier(criterion = "entropy", random_state = 100,max_depth = None, min_samples_leaf = 5) 
  
    # Performing training 
    clf_entropy.fit(X_train, y_train) 
    return clf_entropy 
  
  
# Function to make predictions 
def prediction(X_test, clf_object): 
  
    # Predicton on test with giniIndex 
    y_pred = clf_object.predict(X_test) 
    print("Predicted values:") 
    print(y_pred) 
    return y_pred 
      
# Function to calculate accuracy 
def cal_accuracy(y_test, y_pred): 
      
    print("Confusion Matrix: ", 
        confusion_matrix(y_test, y_pred)) 
      
    print ("Accuracy : ", 
    accuracy_score(y_test,y_pred)*100) 
      
    print("Report : ", 
    classification_report(y_test, y_pred)) 
  
if __name__=="__main__": 
    # Building Phase 
    data = importdata() 
    X, Y, X_train, X_test, y_train, y_test = splitdataset(data) 
    clf_gini = train_using_gini(X_train, X_test, y_train) 
    clf_entropy = tarin_using_entropy(X_train, X_test, y_train) 
      
    # Operational Phase 
    print("Results Using Gini Index:") 
      
    # Prediction using gini 
    y_pred_gini = prediction(X_test, clf_gini) 
    cal_accuracy(y_test, y_pred_gini) 
      
    print("Results Using Entropy:") 
    # Prediction using entropy 
    y_pred_entropy = prediction(X_test, clf_entropy) 
    cal_accuracy(y_test, y_pred_entropy) 
      
      

Dataset Lenght:  22425
Dataset Shape:  (22425, 7)
Dataset:     wk_c  wk_r  wr_c  wr_r  bk_c  bk_r moves
0     1     1     2     3     3     2  draw
1     1     1     3     1     3     2  draw
2     1     1     3     1     4     1  draw
3     1     1     3     1     4     2  draw
4     1     1     3     2     3     1  draw
Results Using Gini Index:
Predicted values:
['draw' 'draw' 'draw' ... 'thirteen' 'twelve' 'draw']
Confusion Matrix:  [[625  13  40   9   0  20  15   0  19   2  19  40   0  37   0   2]
 [ 20 306   6   1   0   1  35   0  29   1   8  12   0   6   0   0]
 [ 34   8 571   1   0  10  15   1   4   6  50  62   0  92   0   0]
 [  2   2   1 110   6   0   2   3   7   9   1   0   1   0   3   0]
 [  0   4   0  10  43   0   1   1   2   4   0   1  11   0   1   0]
 [ 25   0  14   0   0 342   0   0   1   0   2  48   0  12   0   0]
 [ 32  29  27   2   1   0 365   1  13   7  36   8   0  13   0   0]
 [  1   0   0   2   0   0   0  12   4   1   0   0   2   0   0   0]
 [ 17  16   5   3   0  