In [3]:
#import sys
#!{sys.executable} -m pip install matplotlib
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
  
# reading csv file and extracting class column to y. 
balance_data = pd.read_csv( '/home/karthik/anaconda_python/411631_kelab_record/411631_python_using/classification/support Vector Machine/chess.txt', sep= ',') 
      
new_data = {"wk_c":{"a":1,"b":2,"c":3,"d":4,"e":5,"f":6,"g":7,"h":8},
                 "wr_c":{"a":1,"b":2,"c":3,"d":4,"e":5,"f":6,"g":7,"h":8},
                 "bk_c":{"a":1,"b":2,"c":3,"d":4,"e":5,"f":6,"g":7,"h":8}}
balance_data.replace(new_data,inplace=True)
 
a = np.array(balance_data)
x = a[:,:6]
y  = a[:,6] # classes having 0 and 1 
print(x)

# import support vector classifier 
from sklearn.svm import SVC # "Support Vector Classifier" 
clf = SVC(kernel='linear') 
  
# fitting x samples and y classes 
clf.fit(x, y) 

#After being fitted, the model can then be used to predict new values:
print(clf.predict([[1, 3, 3, 4, 4, 1]]))

[[1 1 2 3 3 2]
 [1 1 3 1 3 2]
 [1 1 3 1 4 1]
 ...
 [2 2 4 8 6 4]
 [2 2 4 8 6 5]
 [2 2 4 8 7 3]]
['fourteen']
